name: CI
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    checks:
        name: Checks
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1

            - name: Install dependencies
              run: bun install

            - name: Generate database types
              run: cd apps/api && bun db:gen

            - name: Generate API types
              run: bun gen

            - name: Run checks
              run: bun checks

            - name: Test API
              run: bun test:api

            - name: Test Commitment
              run: bun test:commitment
