name: CI
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    checks:
        name: Checks
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v1
            - run: bun install
            - run: cd apps/api && bun db:gen
            - run: bun gen
            - run: bun checks
